### ISSUE TITLE
Order search results by torrent creation date (desc)

### ISSUE THREAD

**Issue by scriptzteam** [retonato/torrenthistory-public#11]
Order search by torrent id desc ;) So when searching it, sort by latest id..

**Comment by retonato** [comment]
That's possible, but that would make search slightly slower (at the moment, when user just presses "Search", database engine just gets the first 100 matching results in that order, which they are located in the database; if I add "ORDER BY torrent_id" to the query, it will need to get all results and sort them).
By the way, torrent_id is more or less random, why do you want to see highest ids first? Some of them are recently found torrents, true, but many of them just recently imported torrents, which were created long time ago.
Sooner or later I will add "created" date to most torrents (https://github.com/retonato/torrenthistory-public/issues/4), wouldn't it be better to sort search results by it (desc)?

**Comment by scriptzteam** [comment]
Sure order by created date/time would be cool too :-)

**Comment by retonato** [comment]
Done.
