### ISSUE TITLE
Add torrent Infohash

### ISSUE THREAD

**Issue by activoice** [retonato/torrenthistory-public#12]
Are you storing the infohash for each torrent in your database? If so that would help someone download the Torrent as you don't want to store the actual torrent files.

**Comment by retonato** [comment]
Some features cannot be implemented for legal reasons: https://torrenthistory.org/docs/features-which-will-not-be-implemented/ :
"Anything, which makes downloading possible. I cannot add links to torrent files, magnet links, infohashes, links to sources, active source site names, etc."
